# Site settings
baseurl = "https://translatedmedicine.netify.com/"
languageCode = "en-us"
title = "Translated Medicine | Jorge A Rodriguez MD"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[params]
	name = "Jorge A Rodriguez MD"
	description = "Bridging the digital divide in digital health"
	bio = "Medicine | Social Justice | Technology"
	# Enter optionally your twitter account
	twitter = "translatedmed"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am a physician and informatician."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/translatedmed"
    linkedin = "https://www.linkedin.com/in/jorgearodriguezmd"
    #facebook = "https://www.facebook.com/"
    #github   = "https://www.github.com/"
    #dribble  = "https://www.dribbble.com/"
